owner: anthonydillon
repo: canonical-sites-monitor

sites:
  - name: ubuntu.com
    url: https://ubuntu.com
  - name: ubuntu.com/advantage
    url: https://ubuntu.com/advantage
  - name: ubuntu.com/server/docs
    url: https://ubuntu.com/server/docs
  - name: ubuntu.com/blog
    url: https://ubuntu.com/blog
  - name: ubuntu.com/tutorials
    url: https://ubuntu.com/tutorials
  - name: canonical.com
    url: https://canonical.com
  - name: canonical.com/careers
    url: https://canonical.com/careers
  - name: maas.io
    url: https://maas.io
  - name: maas.io/docs
    url: https://maas.io/docs
  - name: dqlite.io
    url: https://dqlite.io
  - name: dqlite.io/docs
    url: https://dqlite.io/docs
  - name: charmhub.io
    url: https://charmhub.io
  - name: jaas.ai
    url: https://jaas.ai

status-website:
  logoUrl: https://assets.ubuntu.com/v1/ff7dd096-logo-canonical-aubergine.svg
  name: Canonical sites monitor
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
